### ISSUE TITLE
Uploads Not Working

### ISSUE THREAD

**Issue by pageb018** [linuxserver/docker-snipe-it#15]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

 
Uploading either branding or assets images does not function correctly. While the upload seems to complete, ie. I can see the asset in the file system of the container, the asset is not correctly applied to the web interface. The same issue occurs when uploading images to a specific asset. 

------------------------------

## Expected Behavior
Uploading asset or branding images should be reflected in the web interface and/or the specific asset page. 

## Current Behavior
When uploading branding images, no change to branding occurs. 

When uploading asset images, broken image box appears. 

## Steps to Reproduce

1. Create new Snipe application using standard docker-compose supplied
2. Upload either branding or asset image

## Environment
**OS:** Ubuntu Server 20.04.1 LTS
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

Container is run via the compose file supplied on the docker hub page. Bind mounts are used for volumes, PID and GUID are both set 1000

## Command used to create docker container (run/create/compose/screenshot)

https://imgur.com/TJk2wW4

```
version: "3"
services:
  mysql:
    image: mysql:5
    container_name: snipe_mysql
    restart: always
    volumes:
      - ./config/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=********
      - MYSQL_USER=snipe
      - MYSQL_PASSWORD=*******
      - MYSQL_DATABASE=snipe
  snipeit:
    image: linuxserver/snipe-it:latest
    container_name: snipe-it
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./config/snipe:/config
    environment:
      - APP_URL=snipe.********.com
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=snipe
      - MYSQL_USER=snipe
      - MYSQL_PASSWORD=*******
      - PGID=1000
      - PUID=1000
      - APP_TIMEZONE=America/New_York
      - MAIL_PORT_587_TCP_ADDR=email-smtp.us-east-1.amazonaws.com
      - MAIL_PORT_587_TCP_PORT=587
      - MAIL_ENV_FROM_ADDR=inventory@********.com
      - MAIL_ENV_FROM_NAME=*******
      - MAIL_ENV_ENCRYPTION=tls
      - MAIL_ENV_USERNAME=*******
      - MAIL_ENV_PASSWORD=********
      # - UMASK=022 (have tried with both UMASK set and not set.
    ports:
      - "80:80"
      - "443:443"

``` 

## Docker logs

N/A 

Logs do not show any changes.
