### ISSUE TITLE
Gateway timeout 504 on setting up Database

### ISSUE THREAD

**Issue by invertium** [linuxserver/docker-snipe-it#24]
I run my system with docker-compose on ubuntu with the following compose file:

```
version: "3"
services:
  mysql:
    image: linuxserver/mariadb
    container_name: snipe_mysql
    restart: always
    volumes:
      - ./mysqldata:/config
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Berlin
      - MYSQL_ROOT_PASSWORD=snipe
      - MYSQL_USER=snipe
      - MYSQL_PASSWORD=snipe
      - MYSQL_DATABASE=snipe
  snipeit:
    image: linuxserver/snipe-it:latest
    container_name: snipe-it
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./snipeitconfig:/config
    environment:
      - NGINX_APP_URL=server-name:8081
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=snipe
      - MYSQL_USER=snipe
      - MYSQL_PASSWORD=snipe
      - PGID=100
      - PUID=1000
    ports:
      - "8081:80"
```

However when i go through the setup i get a 504 Error at http://stabl-trocken:8081/setup/migrate?

I already checked that the UID and the GID are the one of the user im running docker from. the two folders are created when the docker container is started. 

I do have another mariadb container running on the same machine. I tried to place them in different networks but I haven't been able to figure out if that is even the issue. The setup shows a working connection to the database.
