### ISSUE TITLE
ENV vars dont used by app

### ISSUE THREAD

**Issue by wuast94** [linuxserver/docker-snipe-it#30]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
ENV vars should work

## Current Behavior
I can check inside container that the envs get set inside container correctly
but on the setup page i see that he try to connect to a standard value:
Access denied for user 'snipe'@'172.17.0.1'
i set another user and another ip adress. i checked the .env file inside container too and all looks right

## Steps to Reproduce
start docker compose as in readme:

```
    snipeit:
        image: linuxserver/snipe-it:latest
        container_name: snipe-it
        restart: always
        depends_on:
            - mariadbsnipe
        volumes:
            - /mnt/user/appdata/snipe-it:/config
        environment:
            - NGINX_APP_URL=192.168.178.26:8084
            - MYSQL_PORT_3306_TCP_ADDR=192.168.178.26
            - MYSQL_PORT_3306_TCP_PORT=3126
            - MYSQL_DATABASE=snipe
            - MYSQL_USER=testuser
            - MYSQL_PASSWORD=testpassword5698
            - PGID=1000
            - PUID=1000
        ports:
            - "8084:80"
```
            
## Environment
**OS:** Unraid 
**CPU architecture:** x86_64
**How docker service was installed:**

## Command used to create docker container (run/create/compose/screenshot)

see above
## Docker logs

```
         | |  ___   _    __

         | | / __| | |  /  \

         | | \__ \ | | | () |

         |_| |___/ |_|  \__/



Brought to you by linuxserver.io

-------------------------------------


To support the app dev(s) visit:

Snipe-IT: https://snipeitapp.com/donate


To support LSIO projects visit:

https://www.linuxserver.io/donate/

-------------------------------------

GID/UID

-------------------------------------


User uid:    1000

User gid:    1000

-------------------------------------


[cont-init.d] 10-adduser: exited 0.

[cont-init.d] 20-config: executing... 

[cont-init.d] 20-config: exited 0.

[cont-init.d] 30-keygen: executing... 

generating self-signed keys in /config/keys, you can replace these with your own keys if required

Generating a RSA private key

...............+++++

........................+++++

writing new private key to '/config/keys/cert.key'

-----

[cont-init.d] 30-keygen: exited 0.

[cont-init.d] 40-config: executing... 

Generating SnipeIT app key for first run

App Key set to base64:wtrsE6CuOlNSzEfPYUlSSB0X//lCTumqryqDQP5lNco= you can modify the file to update /config/SNIPE_IT_APP_KEY.txt

[cont-init.d] 40-config: exited 0.

[cont-init.d] 90-custom-folders: executing... 

[cont-init.d] 90-custom-folders: exited 0.

[cont-init.d] 99-custom-files: executing... 

[custom-init] no custom files found exiting...

[cont-init.d] 99-custom-files: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.

[cont-finish.d] executing container finish scripts...

[cont-finish.d] done.

[s6-finish] waiting for services.

[s6-finish] sending all processes the TERM signal.

[s6-finish] sending all processes the KILL signal and exiting.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] 01-envfile: executing... 

[cont-init.d] 01-envfile: exited 0.

[cont-init.d] 10-adduser: executing... 

usermod: no changes


-------------------------------------

          _         ()

         | |  ___   _    __

         | | / __| | |  /  \

         | | \__ \ | | | () |

         |_| |___/ |_|  \__/



Brought to you by linuxserver.io

-------------------------------------


To support the app dev(s) visit:

Snipe-IT: https://snipeitapp.com/donate


To support LSIO projects visit:

https://www.linuxserver.io/donate/

-------------------------------------

GID/UID

-------------------------------------


User uid:    1000

User gid:    1000

-------------------------------------


[cont-init.d] 10-adduser: exited 0.

[cont-init.d] 20-config: executing... 

[cont-init.d] 20-config: exited 0.

[cont-init.d] 30-keygen: executing... 

using keys found in /config/keys

[cont-init.d] 30-keygen: exited 0.

[cont-init.d] 40-config: executing... 

[cont-init.d] 40-config: exited 0.

[cont-init.d] 90-custom-folders: executing... 

[cont-init.d] 90-custom-folders: exited 0.

[cont-init.d] 99-custom-files: executing... 

[custom-init] no custom files found exiting...

[cont-init.d] 99-custom-files: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.
```
