### ISSUE TITLE
Device images lost after update

### ISSUE THREAD

**Issue by caheredia** [linuxserver/docker-snipe-it#38]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Device images should be displayed when viewing dashboard

## Current Behavior
No images rendered, only the name of devices. 
When I click on the device image link I get the following message: "Failed to load image" followed by the location of the image

## Steps to Reproduce
1. Updated to V5.4.1 build 6746 (g3e22dce11) 
2. Click on device image name (What used to render as an image) 

## Environment
**OS:Docker on ubuntu LTS**
**CPU architecture:** x86_64
**How docker service was installed: Docker install script**

## Command used to create docker container (run/create/compose/screenshot)
```yaml
  mysql:
    image: linuxserver/mariadb
    container_name: snipe_mysql
    restart: always
    volumes:
      - ./snipe_it/mysql/config:/config
    environment:
      TZ: 'America/Los_Angeles'
      PUID: 1000
      PGID: 1000
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: snipe
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: snipe
    networks:
      - app_net
  snipeit:
    image: linuxserver/snipe-it
    container_name: snipe-it
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./snipe_it/config:/config
    environment:
      APP_URL: 192.168.1.214:8080
      MYSQL_PORT_3306_TCP_ADDR: mysql
      MYSQL_PORT_3306_TCP_PORT: 3306
      MYSQL_DATABASE: snipe
      MYSQL_USER: snipe
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      PGID: 1000
      PUID: 1000
    networks:
      - app_net
```

<img width="691" alt="Screen Shot 2022-03-12 at 9 08 41 PM" src="https://user-images.githubusercontent.com/28638529/158046272-889c3637-86c7-488d-a1d3-ca850d3af22e.png">
