### ISSUE TITLE
Server Error 500 after fresh install

### ISSUE THREAD

**Issue by Surgical71** [linuxserver/docker-snipe-it#47]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

 Server error 500 after fresh docker-compose install

------------------------------

## Current Behavior
-- Server error 500. Both App container and SQL container runs as expected and provides a IP

## Steps to Reproduce
1. Launched stack via Portainer and docker compose
2. Connected to container via NGINX proxy manager
3.
4.

## Environment
**OS:** 
-- Ubuntu Server
**CPU architecture:** 
-- arm64
**How docker service was installed:**
-- Via Portainer 

## Command used to create docker container (run/create/compose/screenshot)

version: "3"
services:
  mysql:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: snipe_mysql
    restart: unless-stopped
    volumes:
      - /home/ubuntu/DockerCompose/snipe/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=(My password)
      - MYSQL_USER=snipe
      - MYSQL_PASSWORD=(My password)
      - MYSQL_DATABASE=snipe
  snipeit:
    image: lscr.io/linuxserver/snipe-it:latest
    container_name: snipe-it
    restart: unless-stopped
    depends_on:
      - mysql
    volumes:
      - /home/ubuntu/DockerCompose/snipe/config:/config
    environment:
      - APP_URL=https://inventory.venncubed.com
      - MAIL_PORT_587_TCP_ADDR=smtp.office365.com
      - MAIL_PORT_587_TCP_PORT=587
      - MAIL_ENV_FROM_ADDR=(my domain email)
      - MAIL_ENV_FROM_NAME=Snipe
      - MAIL_ENV_ENCRYPTION=tls
      - MAIL_ENV_USERNAME=(my domain email)
      - MAIL_ENV_PASSWORD=(My password)
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=snipe
      - MYSQL_USER=snipe
      - MYSQL_PASSWORD=(My password)
      - PGID=1000
      - PUID=1000
      - TZ=ZA
    ports:
      - "8084:80"
      - "8083:443"

## Docker logs

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support the app dev(s) visit:
Snipe-IT: https://snipeitapp.com/donate
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------
cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/20-config
cont-init: info: /etc/cont-init.d/20-config exited 0
cont-init: info: running /etc/cont-init.d/30-keygen
using keys found in /config/keys
cont-init: info: /etc/cont-init.d/30-keygen exited 0
cont-init: info: running /etc/cont-init.d/40-config
cont-init: info: /etc/cont-init.d/40-config exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
[custom-init] No custom files found, skipping...
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-mods: starting
s6-rc: info: service init-mods successfully started
s6-rc: info: service init-mods-package-install: starting
s6-rc: info: service init-mods-package-install successfully started
s6-rc: info: service init-mods-end: starting
s6-rc: info: service init-mods-end successfully started
s6-rc: info: service init-services: starting
s6-rc: info: service init-services successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun cron (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
services-up: info: copying legacy longrun php-fpm (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started

**Comment by GooRoo** [comment]
I've just come here to create exactly same issue. Was trying to do something with it the whole day yesterday with no luck.
My `docker-compose.yaml` is nearly the same too:
```yaml
---
version: "2.1"
services:
  db:
    image: lscr.io/linuxserver/mariadb:latest
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Berlin
      - MYSQL_ROOT_PASSWORD=<root-pass>
      - MYSQL_DATABASE=snipeit
      - MYSQL_USER=snipeit
      - MYSQL_PASSWORD=<pass>
    volumes:
      - <data-folder>/db:/config
    restart: unless-stopped
  
  web:
    image: lscr.io/linuxserver/snipe-it:latest
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Berlin
      - APP_URL=http://192.168.2.10:8080
      - MYSQL_PORT_3306_TCP_ADDR=db
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=snipeit
      - MYSQL_USER=snipeit
      - MYSQL_PASSWORD=<pass>
    volumes:
      - <data-folder>/config:/config
    ports:
      - 8080:80
    restart: unless-stopped
```
